# Generated by Django 5.0.1 on 2024-01-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizclashBackend", "0004_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
