# Generated by Django 5.0.1 on 2024-01-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizclashBackend", "0006_quiz_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
